cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

cask 'atom'
cask 'iterm2'
# cask 'slack'

brew 'git'
brew 'ack'
brew 'coreutils'
brew 'go'
brew 'dep'
brew 'grc'
brew 'hub'
brew 'imagemagick'
brew 'jp2a'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'nave'
brew 'readline'
brew 'postgresql'
# brew 'ruby-build'
# brew 'rbenv'
brew 'shellcheck'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'terminal-notifier'
brew 'fzf'

## not right now
# cask 'firefox'
# cask 'google-chrome'
# cask 'vlc'
# cask 'jumpcut'
# # window management
# cask 'spectacle'
