cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'shellcheck'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'

## not right now
# cask 'adium'
# cask 'steam'
# cask 'iterm2'
# cask '1password'
# cask 'atom'
# cask 'firefox'
# cask 'google-chrome'
# cask 'slack'
# cask 'vlc'
