alias reload!='. ~/.zshrc'
alias bi="brew install"
alias subl="sublime"
alias pulls="open https://github.com/pulls"
alias pi="pod install"
alias ddd='rm -rfd ~/Library/Developer/Xcode/DerivedData/*'
alias gsu='git submodule update'
alias bu="brew update && brew upgrade `brew outdated`"
alias gog="go get"
